apiVersion: v1
kind: Secret
metadata:
  name: mendix-app-secrets
type: Opaque
data:
  admin-password: <ADMIN_PASSWORD?
  db-endpoint: <DATABASE_ENDPOINT>
  license-key: <LICENSE_KEY>
  license-id: <LICENSE_ID>